version: 2.1

jobs:
  build:
    docker:
      #- image: circleci/openjdk:11-jdk-stretch
      - image: cimg/openjdk:13.0
    steps:
      - checkout
      - run: |
          ./gradlew bootJar

workflows:
  version: 2
  workflow:
    jobs:
    - build
